name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Get Version and Name from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          EXTENSION_NAME=$(jq -r .name package.json)
          echo "Extracted version: $VERSION"
          echo "Extracted extension name: $EXTENSION_NAME"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "EXTENSION_NAME=$EXTENSION_NAME" >> $GITHUB_OUTPUT
        shell: bash

      - name: Zip extensions
        run: |
          pnpm zip
          pnpm zip:firefox

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            .output/${{ steps.get_version.outputs.EXTENSION_NAME }}-${{ steps.get_version.outputs.VERSION }}-chrome.zip
            .output/${{ steps.get_version.outputs.EXTENSION_NAME }}-${{ steps.get_version.outputs.VERSION }}-firefox.zip
            .output/${{ steps.get_version.outputs.EXTENSION_NAME }}-${{ steps.get_version.outputs.VERSION }}-sources.zip
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          name: v${{ steps.get_version.outputs.VERSION }}
          tag: v${{ steps.get_version.outputs.VERSION }}
          body: |
            ## Release Notes for v${{ steps.get_version.outputs.VERSION }}

            This release includes the following artifacts:

            *   Chrome Extension
            *   Firefox Extension
            *   Firefox Sources (for AMO submission)

            Please see the [commit history](https://github.com/${{ github.repository }}/commits/v${{ steps.get_version.outputs.VERSION }}) for more details.

      #- name: Submit to stores
      #  run: |
      #    pnpm wxt submit \
      #      --chrome-zip .output/${{ steps.get_version.outputs.EXTENSION_NAME }}-${{ steps.get_version.outputs.VERSION }}-chrome.zip \
      #      --firefox-zip .output/${{ steps.get_version.outputs.EXTENSION_NAME }}-${{ steps.get_version.outputs.VERSION }}-firefox.zip --firefox-sources-zip .output/${{ steps.get_version.outputs.EXTENSION_NAME }}-${{ steps.get_version.outputs.VERSION }}-sources.zip
      #  env:
      #    CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
      #    CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
      #    CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
      #    CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
      #    FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
      #    FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
      #    FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
